version: "3"
services:
  node:
    image: node:${NODE_VERSION}
    privileged: true
    volumes:
      #- ${SOURCE_DIR}:/var/www/html/:rw
      - ${SOURCE_DIR}:${APP_CODE_PATH_CONTAINER}:rw
    environment:
      TZ: "$TZ"  
    networks:
      - default

  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    privileged: true
    volumes:
      - ${SOURCE_DIR}:${APP_CODE_PATH_CONTAINER}:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    environment:
      TZ: "$TZ"    
    networks:
      - default

  php-fpm:
    build:
      context: ./config/php/
      args:
        PHP_VERSION: ${PHP71_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP71_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php71.sh
        TZ: "$TZ"
    ports:
      - "${PHP71_HOST_PORT}:9000"
    privileged: true
    volumes:
      - ${SOURCE_DIR}:${APP_CODE_PATH_CONTAINER}:rw
      - ${PHP71_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP71_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP71_LOG_DIR}:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"    
    networks:
      - default

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    environment:
      TZ: "$TZ"    
    networks:
      - default
      
networks:
  default:


